// TODO Implement this library.
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFyG__yYHFgRHkv7r_fDGuFGcrDZqLBL4',
    appId: '1:59433856072:web:5a9568d302d7ddf9d07c7d',
    messagingSenderId: '59433856072',
    projectId: 'hortifruti-adm',
    authDomain: 'hortifruti-adm.firebaseapp.com',
    databaseURL: 'https://hortifruti-adm-default-rtdb.firebaseio.com',
    storageBucket: 'hortifruti-adm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsNEmyIyYDDbmnGpao4lRdNZDYZuBrHRI',
    appId: '1:59433856072:android:d400b382382f091cd07c7d',
    messagingSenderId: '59433856072',
    projectId: 'hortifruti-adm',
    databaseURL: 'https://hortifruti-adm-default-rtdb.firebaseio.com',
    storageBucket: 'hortifruti-adm.firebasestorage.app',
  );

}
